CFLAGS += -fopenmp -Iinclude/rt/openmp

obj-y += \
	sysconf.o \
	qsort.o \
	pthread_helper.o \
	omptest.o



#obj-y += openmpbench_C_v31/
#obj-y += streamcluster/
obj-$(NAUT_CONFIG_OPENMP_RT) += pthreadlib/

